
import "./globals.css";
import Navbar from "../components/Navbar";

export const metadata = {
  title: "Mindmates",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={"true"} />
        <link href="https://fonts.googleapis.com/css2?family=Baloo+2:wght@400..800&family=Outfit:wght@100..900&display=swap" rel="stylesheet" />
      </head>
      <body
        className={` antialiased`}
      >
        <main>{children}</main>
        <Navbar />
      </body>
    </html>
  );
}
